plugins {
    id 'java'
    id 'net.neoforged.moddev' version '2.0.146'
}

group = 'dev.fpbcraft'
version = providers.gradleProperty('mod_version').get()

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
    maven { url = 'https://maven.createmod.net' }
    maven { url = 'https://maven.ithundxr.dev/snapshots' }
}

neoForge {
    version = providers.gradleProperty('neoforge_version').get()
    mods {
        bluemap_create_railway {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") {
        transitive = false
    }
    implementation("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    implementation("com.tterrag.registrate:Registrate:${registrate_version}")
}

tasks.named('processResources') {
    inputs.property 'version', project.version
    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}

base {
    archivesName = 'bluemap-create-railway'
}
